"""add attempts to game_sessions

Revision ID: b9cf0d6643a0
Revises: c68542d0a467
Create Date: 2026-09-06 22:51:23.339233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cf0d6643a0'
down_revision: Union[str, None] = 'c68542d0a467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'attempts')
    # ### end Alembic commands ###
